apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
    # config.js: |
    #     window._env_ = {
    #     VITE_API_BASE_URL: {{ .Values.config.backendUrl }}
    #     };
    VITE_API_BASE_URL: {{ .Values.config.backendUrl | quote }}
