apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
  namespace: default
spec:
  serviceAccountName: secret-manager
  restartPolicy: Never
  containers:
  - name: aws-cli
    image: amazon/aws-cli
    command: ["sleep", "3600"]
