apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
    PGHOST: "postgres"
    PGPORT: "5432"
    PGDATABASE: "fhv"