apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: database-secret
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "pg-db-secret"
          objectType: "secretsmanager"
