apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
    PGHOST: "css-db.ct6wueoyusxp.eu-north-1.rds.amazonaws.com:5432"
    PGPORT: "5432"
    PGDATABASE: "fhv"