apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    app: postgresql
    role: database
  ports:
    - port: 5432
      name: postgres
      protocol: TCP
      targetPort: 5432
  clusterIP: None