# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: database
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: git@github.com:Isrealade/nyc_fhv_analytics-sndx.git
#     targetRevision: HEAD
#     path: infrastructure/charts/postgresql
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: default
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true