apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: "501818865030.dkr.ecr.us-east-1.amazonaws.com/frontend"
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/image-backend.update-strategy: "digest"
spec:
  project: default
  source:
    repoURL: git@github.com:Isrealade/nyc_fhv_analytics-sndx.git
    targetRevision: HEAD
    path: infrastructure/charts/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
